# Generated by Django 4.2 on 2025-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.TextField(default='NA')),
                ('authors', models.TextField(default='NA')),
                ('publish_time', models.IntegerField(default=2024)),
                ('journal', models.TextField(default='NA')),
                ('doi', models.CharField(default='NA', max_length=200)),
                ('species', models.CharField(default='NA', max_length=100)),
                ('symbiont', models.CharField(default='NA', max_length=100)),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'db_table': 'article',
                'ordering': ['id'],
            },
        ),
    ]
