# Generated by Django 4.2 on 2024-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='NA', max_length=200)),
                ('authors', models.TextField(default='NA')),
                ('publish_time', models.IntegerField(default=2024)),
                ('journal', models.CharField(default='NA', max_length=100)),
                ('doi', models.CharField(default='NA', max_length=100, unique=True)),
                ('wos', models.CharField(default='NA', max_length=100)),
                ('accession_numbers', models.TextField(default='NA')),
                ('species', models.CharField(default='NA', max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
