# Generated by Django 4.2 on 2024-12-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='accession_numbers',
        ),
        migrations.RemoveField(
            model_name='article',
            name='wos',
        ),
        migrations.AddField(
            model_name='article',
            name='symbiont',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
