# Generated by Django 4.2 on 2024-12-16 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_accession_numbers_remove_article_wos_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['id'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(default='NA', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='journal',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterField(
            model_name='article',
            name='species',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='symbiont',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='NA'),
        ),
        migrations.AlterModelTable(
            name='article',
            table='article',
        ),
    ]
