# Generated by Django 4.2 on 2024-12-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='doi',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
