# Generated by Django 4.2 on 2025-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(help_text='species', max_length=200, unique=True)),
                ('order', models.CharField(help_text='order', max_length=100)),
                ('family', models.CharField(help_text='family', max_length=100)),
                ('subfamily', models.CharField(blank=True, help_text='subfamily', max_length=100, null=True)),
                ('genus', models.CharField(help_text='genus', max_length=100)),
                ('common_name', models.CharField(blank=True, help_text='common name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='description text')),
                ('figure_source', models.CharField(blank=True, help_text='Image source and license information', max_length=500, null=True)),
                ('genome_id', models.CharField(blank=True, help_text='Genome ID', max_length=20, null=True)),
                ('genome_level', models.CharField(blank=True, help_text='Genome assembly level', max_length=20, null=True)),
                ('busco', models.TextField(blank=True, help_text='BUSCO assessment results', null=True)),
            ],
            options={
                'verbose_name_plural': 'hosts',
                'ordering': ['species'],
            },
        ),
    ]
