# Generated by Django 4.2 on 2024-12-24 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='host',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='host',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='host',
            name='common_name',
            field=models.CharField(blank=True, help_text='common name', max_length=200),
        ),
        migrations.AlterField(
            model_name='host',
            name='description',
            field=models.TextField(blank=True, help_text='description text'),
        ),
        migrations.AlterField(
            model_name='host',
            name='family',
            field=models.CharField(help_text='family', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='genus',
            field=models.CharField(help_text='genus', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='order',
            field=models.CharField(help_text='order', max_length=100),
        ),
        migrations.AlterField(
            model_name='host',
            name='species',
            field=models.CharField(help_text='species', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='subfamily',
            field=models.CharField(blank=True, help_text='subfamily', max_length=100, null=True),
        ),
    ]
