# Generated by Django 4.2 on 2025-01-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('host', '0002_remove_host_created_at_remove_host_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='busco',
            field=models.TextField(blank=True, help_text='BUSCO assessment results', null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='figure_source',
            field=models.CharField(blank=True, help_text='Image source and license information', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='genome_id',
            field=models.CharField(blank=True, help_text='Genome ID', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='genome_level',
            field=models.CharField(blank=True, help_text='Genome assembly level', max_length=20, null=True),
        ),
    ]
