var data = [
    { name: 'Wolbachia', type: 'symbiont' },
    { name: 'Unknown', type: 'symbiont' },
    { name: 'Enterococcus mundtii', type: 'symbiont' },
    { name: 'Craurococcus', type: 'symbiont' },
    { name: 'Enterobacter asburiae YT1', type: 'symbiont' },
    { name: 'Bacillus sp. YP1', type: 'symbiont' },
    { name: 'Diaphorobacter', type: 'symbiont' },
    { name: 'Pantoea', type: 'symbiont' },
    { name: 'Tanticharoenia', type: 'symbiont' },
    { name: 'Klebsiella pneumoniae ZM1', type: 'symbiont' },
    { name: 'Bacillus subtillis', type: 'symbiont' },
    { name: 'Variovorax', type: 'symbiont' },
    { name: 'Duganella', type: 'symbiont' },
    { name: 'Aeromonas sp. TM1', type: 'symbiont' },
    { name: 'Candidatus Rickettsia_Torix_Bemisia_tabaci', type: 'symbiont' },
    { name: 'Burkholderia cepacia', type: 'symbiont' },
    { name: 'Candidatus Shikimatogenerans', type: 'symbiont' },
    { name: 'Candidatus Macropleicola muticae', type: 'symbiont' },
    { name: 'Rhodococcus ruber', type: 'symbiont' },
    { name: 'Citrobacter', type: 'symbiont' },
    { name: 'Serratia marcescens', type: 'symbiont' },
    { name: 'Mycobacterium', type: 'symbiont' },
    { name: 'Kosakonia', type: 'symbiont' },
    { name: 'Exiguobacterium sp. YT2', type: 'symbiont' },
    { name: 'Massilia', type: 'symbiont' },
    { name: 'Acidimonas', type: 'symbiont' },
    { name: 'Burkholderia', type: 'symbiont' },
    { name: 'Saccharibacter', type: 'symbiont' },
    { name: 'Bacillus circulans', type: 'symbiont' },
    { name: 'Plinachtus bicoloripes', type: 'host' },
    { name: 'Corcyra cephalonica', type: 'host' },
    { name: 'Yemma exilis', type: 'host' },
    { name: 'Pachygrontha antennata', type: 'host' },
    { name: 'Donacia proxima', type: 'host' },
    { name: 'Pseudomyrmex ferrugineus', type: 'host' },
    { name: 'Lepidiota mansueta', type: 'host' },
    { name: 'Pachybrachius luridus', type: 'host' },
    { name: 'Leptocorisa chinensis', type: 'host' },
    { name: 'Plateumaris pusilla', type: 'host' },
    { name: 'Tetraponera binghami', type: 'host' },
    { name: 'Donacia vulgaris', type: 'host' },
    { name: 'Paraplesius unicolor', type: 'host' },
    { name: 'Chauliops fallax', type: 'host' },
    { name: 'Donacia cincticornis', type: 'host' },
    { name: 'Cletus trigonus', type: 'host' },
    { name: 'Osmia bicornis', type: 'host' },
    { name: 'Donacia tomentosa', type: 'host' },
    { name: 'Acanthocoris sordidus.', type: 'host' },
    { name: 'Metochus abbreviatus', type: 'host' },
    { name: 'Riptortus linearis', type: 'host' },
    { name: 'Laodelphax striatellus', type: 'host' },
    { name: 'linachtus bicoloripes', type: 'host' },
    { name: 'Piocoris varius', type: 'host' },
    { name: 'Paraeucosmetus pallicornis', type: 'host' },
    { name: 'Pangorus albomaculatus ', type: 'host' },
    { name: 'Donacia fulgens', type: 'host' },
    { name: 'Donacia bicoloricornis', type: 'host' },
    { name: 'Cletus punctigerr', type: 'host' },
    { name: 'Bombus sonorus', type: 'host' },
    { name: 'Donacia simplex', type: 'host' },
    { name: 'Homoeocerus dilatatus', type: 'host' },
    { name: 'Donacia provostii', type: 'host' },
    { name: 'Spodoptera littoralis', type: 'host' },
    { name: 'Donacia marginata', type: 'host' },
    { name: 'Tropidothorax belogolowi', type: 'host' },
    { name: 'Donacia clavipes', type: 'host' },
    { name: 'Horridipamera nietneri', type: 'host' },
    { name: 'Lethaeus assamensis', type: 'host' },
    { name: 'Plateumaris sericea', type: 'host' },
    { name: 'Spilostethus hospes', type: 'host' },
    { name: 'Leptocorisa oratoria', type: 'host' },
    { name: 'Graptostethus servus', type: 'host' },
    { name: 'Plodia interpunctella', type: 'host' },
    { name: 'Donacia dentata', type: 'host' },
    { name: 'Plateumaris rustica', type: 'host' },
    { name: 'Plateumaris consimilis', type: 'host' },
    { name: 'Aethalotus nigriventris ', type: 'host' },
    { name: 'Caenocoris dimidiatus', type: 'host' },
    { name: 'Homoeocerus unipunctatus  ', type: 'host' },
    { name: 'Homoeocerus marginiventris', type: 'host' },
    { name: 'Donacia sparganii', type: 'host' },
    { name: 'Bemisia tabaci', type: 'host' },
    { name: 'Pseudomyrmex gracilis', type: 'host' },
    { name: 'Horridipamera inconspicua', type: 'host' },
    { name: 'Geocoris proteus', type: 'host' },
    { name: 'Molipteryx fuliginosa', type: 'host' },
    { name: 'Apis mellifera', type: 'host' },
    { name: 'Neolethaeus dallasi', type: 'host' },
    { name: 'Donacia cinerea', type: 'host' },
    { name: 'Leptocorisa acuta', type: 'host' },
    { name: 'Macroplea appendiculata', type: 'host' },
    { name: 'Pylorgus colon', type: 'host' },
    { name: 'Cletus rusticus', type: 'host' },
    { name: 'Leptoglossus australis', type: 'host' },
    { name: 'Nysius plebeius', type: 'host' },
    { name: 'Nilaparvata lugens', type: 'host' },
    { name: 'Plateumaris braccata', type: 'host' },
    { name: 'Donacia semicuprea', type: 'host' },
    { name: 'Riptortus pedestris', type: 'host' },
    { name: 'Lagria villosa', type: 'host' },
    { name: 'Malcus japonicus', type: 'host' },
    { name: 'Neohaemonia nigricornis', type: 'host' },
    { name: 'Metatropis rufescens', type: 'host' },
    { name: 'Anacanthocoris striicornis', type: 'host' },
    { name: 'Psylliodes chrysocephala', type: 'host' },
    { name: 'Plinachtus basalis', type: 'host' },
    { name: 'Dasynus coccocinctus', type: 'host' },
    { name: 'Nicrophorus concolor', type: 'host' },
    { name: 'Oncopeltus nigriceps', type: 'host' },
    { name: 'Thunbergia sanguinaria', type: 'host' },
    { name: 'Hygia opaca', type: 'host' },
    { name: 'Lagria hirta', type: 'host' },
    { name: 'Panaorus japonicus ', type: 'host' },
    { name: 'Paradasynus spinosus', type: 'host' },
    { name: 'Daclera levana', type: 'host' },
    { name: 'Lyctus brunneus', type: 'host' },
    { name: 'Paromius exiguus', type: 'host' },
    { name: 'Formica exsecta', type: 'host' },
    { name: 'Donacia thalassina', type: 'host' },
    { name: 'Donacia versicolorea', type: 'host' },
    { name: 'Oryzaephilus surinamensis', type: 'host' },
    { name: 'Megalotomus costalis', type: 'host' },
    { name: 'Notobitus meleagris', type: 'host' },
    { name: 'Riptortus clavatu', type: 'host' },
    { name: 'Dimorphopterus pallipes', type: 'host' },
    { name: 'Donacia piscatrix', type: 'host' },
    { name: 'Hygia lativentris', type: 'host' },
    { name: 'Cavelerius saccharivorus', type: 'host' },
    { name: 'Togo hemipterus', type: 'host' },
    { name: 'Nicrophorus vespilloides', type: 'host' },
    { name: 'Zophobas morio', type: 'host' },
    { name: 'Donacia crassipes', type: 'host' },
    { name: 'Macroplea mutica', type: 'host' },
    { name: 'Tenebrio molitor', type: 'host' },
];

var links = [
    { source: 'Candidatus Shikimatogenerans', target: 'Lyctus brunneus' },
    { source: 'Unknown', target: 'Oryzaephilus surinamensis' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia bicoloricornis' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia cincticornis' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia cinerea' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia clavipes' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia crassipes' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia dentata' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia fulgens' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia marginata' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia piscatrix' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia provostii' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia proxima' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia semicuprea' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia simplex' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia sparganii' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia thalassina' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia tomentosa' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia versicolorea' },
    { source: 'Candidatus Macropleicola muticae', target: 'Donacia vulgaris' },
    { source: 'Candidatus Macropleicola muticae', target: 'Macroplea appendiculata' },
    { source: 'Candidatus Macropleicola muticae', target: 'Macroplea mutica' },
    { source: 'Candidatus Macropleicola muticae', target: 'Neohaemonia nigricornis' },
    { source: 'Candidatus Macropleicola muticae', target: 'Plateumaris braccata' },
    { source: 'Candidatus Macropleicola muticae', target: 'Plateumaris consimilis' },
    { source: 'Candidatus Macropleicola muticae', target: 'Plateumaris pusilla' },
    { source: 'Candidatus Macropleicola muticae', target: 'Plateumaris rustica' },
    { source: 'Candidatus Macropleicola muticae', target: 'Plateumaris sericea' },
    { source: 'Pantoea', target: 'Psylliodes chrysocephala' },
    { source: 'Candidatus Rickettsia_Torix_Bemisia_tabaci', target: 'Bemisia tabaci' },
    { source: 'Wolbachia', target: 'Corcyra cephalonica' },
    { source: 'Wolbachia', target: 'Nilaparvata lugens' },
    { source: 'Wolbachia', target: 'Laodelphax striatellus' },
    { source: 'Wolbachia', target: 'Nilaparvata lugens' },
    { source: 'Burkholderia', target: 'Lagria hirta' },
    { source: 'Burkholderia', target: 'Lagria villosa' },
    { source: 'Burkholderia', target: 'Riptortus pedestris' },
    { source: 'Burkholderia', target: 'Yemma exilis' },
    { source: 'Burkholderia', target: 'Metatropis rufescens' },
    { source: 'Burkholderia', target: 'Chauliops fallax' },
    { source: 'Burkholderia', target: 'Malcus japonicus' },
    { source: 'Burkholderia', target: 'Tropidothorax belogolowi' },
    { source: 'Burkholderia', target: 'Aethalotus nigriventris ' },
    { source: 'Burkholderia', target: 'Caenocoris dimidiatus' },
    { source: 'Burkholderia', target: 'Spilostethus hospes' },
    { source: 'Burkholderia', target: 'Graptostethus servus' },
    { source: 'Burkholderia', target: 'Oncopeltus nigriceps' },
    { source: 'Burkholderia', target: 'Thunbergia sanguinaria' },
    { source: 'Burkholderia', target: 'Nysius plebeius' },
    { source: 'Burkholderia', target: 'Pylorgus colon' },
    { source: 'Burkholderia', target: 'Geocoris proteus' },
    { source: 'Burkholderia', target: 'Piocoris varius' },
    { source: 'Burkholderia', target: 'Dimorphopterus pallipes' },
    { source: 'Burkholderia', target: 'Cavelerius saccharivorus' },
    { source: 'Burkholderia', target: 'Pachybrachius luridus' },
    { source: 'Burkholderia', target: 'Paromius exiguus' },
    { source: 'Burkholderia', target: 'Togo hemipterus' },
    { source: 'Burkholderia', target: 'Paraeucosmetus pallicornis' },
    { source: 'Burkholderia', target: 'Horridipamera inconspicua' },
    { source: 'Burkholderia', target: 'Horridipamera nietneri' },
    { source: 'Burkholderia', target: 'Panaorus japonicus ' },
    { source: 'Burkholderia', target: 'Pangorus albomaculatus ' },
    { source: 'Burkholderia', target: 'Metochus abbreviatus' },
    { source: 'Burkholderia', target: 'Neolethaeus dallasi' },
    { source: 'Burkholderia', target: 'Lethaeus assamensis' },
    { source: 'Burkholderia', target: 'Pachygrontha antennata' },
    { source: 'Burkholderia', target: 'Molipteryx fuliginosa' },
    { source: 'Burkholderia', target: 'Acanthocoris sordidus.' },
    { source: 'Burkholderia', target: 'Leptoglossus australis' },
    { source: 'Burkholderia', target: 'Dasynus coccocinctus' },
    { source: 'Burkholderia', target: 'Notobitus meleagris' },
    { source: 'Burkholderia', target: 'Hygia opaca' },
    { source: 'Burkholderia', target: 'Hygia lativentris' },
    { source: 'Burkholderia', target: 'Homoeocerus dilatatus' },
    { source: 'Burkholderia', target: 'Homoeocerus unipunctatus  ' },
    { source: 'Burkholderia', target: 'Homoeocerus marginiventris' },
    { source: 'Burkholderia', target: 'Anacanthocoris striicornis' },
    { source: 'Burkholderia', target: 'Paradasynus spinosus' },
    { source: 'Burkholderia', target: 'linachtus bicoloripes' },
    { source: 'Burkholderia', target: 'Plinachtus basalis' },
    { source: 'Burkholderia', target: 'Plinachtus bicoloripes' },
    { source: 'Burkholderia', target: 'Cletus trigonus' },
    { source: 'Burkholderia', target: 'Cletus punctigerr' },
    { source: 'Burkholderia', target: 'Cletus rusticus' },
    { source: 'Burkholderia', target: 'Riptortus linearis' },
    { source: 'Burkholderia', target: 'Leptocorisa chinensis' },
    { source: 'Burkholderia', target: 'Leptocorisa acuta' },
    { source: 'Burkholderia', target: 'Leptocorisa oratoria' },
    { source: 'Burkholderia', target: 'Megalotomus costalis' },
    { source: 'Burkholderia', target: 'Daclera levana' },
    { source: 'Burkholderia', target: 'Paraplesius unicolor' },
    { source: 'Burkholderia', target: 'Riptortus clavatu' },
    { source: 'Burkholderia', target: 'Tetraponera binghami' },
    { source: 'Burkholderia', target: 'Formica exsecta' },
    { source: 'Burkholderia', target: 'Pseudomyrmex gracilis' },
    { source: 'Burkholderia', target: 'Pseudomyrmex ferrugineus' },
    { source: 'Burkholderia cepacia', target: 'Apis mellifera' },
    { source: 'Burkholderia cepacia', target: 'Bombus sonorus' },
    { source: 'Burkholderia', target: 'Osmia bicornis' },
    { source: 'Diaphorobacter', target: 'Osmia bicornis' },
    { source: 'Massilia', target: 'Osmia bicornis' },
    { source: 'Duganella', target: 'Osmia bicornis' },
    { source: 'Variovorax', target: 'Osmia bicornis' },
    { source: 'Acidimonas', target: 'Osmia bicornis' },
    { source: 'Acidimonas', target: 'Osmia bicornis' },
    { source: 'Craurococcus', target: 'Osmia bicornis' },
    { source: 'Saccharibacter', target: 'Osmia bicornis' },
    { source: 'Tanticharoenia', target: 'Osmia bicornis' },
    { source: 'Bacillus subtillis', target: 'Osmia bicornis' },
    { source: 'Bacillus circulans', target: 'Osmia bicornis' },
    { source: 'Bacillus sp. YP1', target: 'Plodia interpunctella' },
    { source: 'Enterobacter asburiae YT1', target: 'Plodia interpunctella' },
    { source: 'Rhodococcus ruber', target: 'Tenebrio molitor' },
    { source: 'Exiguobacterium sp. YT2', target: 'Tenebrio molitor' },
    { source: 'Citrobacter', target: 'Tenebrio molitor' },
    { source: 'Kosakonia', target: 'Tenebrio molitor' },
    { source: 'Aeromonas sp. TM1', target: 'Tenebrio molitor' },
    { source: 'Klebsiella pneumoniae ZM1', target: 'Tenebrio molitor' },
    { source: 'Aeromonas sp. TM1', target: 'Zophobas morio' },
    { source: 'Klebsiella pneumoniae ZM1', target: 'Zophobas morio' },
    { source: 'Citrobacter', target: 'Lepidiota mansueta' },
    { source: 'Serratia marcescens', target: 'Nicrophorus vespilloides' },
    { source: 'Mycobacterium', target: 'Nicrophorus concolor' },
    { source: 'Enterococcus mundtii', target: 'Spodoptera littoralis' },
];