# Generated by Django 4.2 on 2024-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbiont',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('record_type', models.CharField(default='NA', max_length=100)),
                ('host_order', models.CharField(db_index=True, default='NA', max_length=100)),
                ('host_family', models.CharField(db_index=True, default='NA', max_length=100)),
                ('host_subfamily', models.CharField(blank=True, db_index=True, default='NA', max_length=100, null=True)),
                ('host_species', models.CharField(blank=True, db_index=True, default='NA', max_length=100, null=True)),
                ('symbiont_phylum', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('symbiont_order', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('symbiont_genus', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('symbiont_rank', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('symbiont_taxon', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('symbiont_name', models.CharField(blank=True, db_index=True, default='NA', max_length=200, null=True)),
                ('classification', models.CharField(default='NA', max_length=100)),
                ('localization', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('function', models.TextField(blank=True, default='NA', null=True)),
                ('transmission_mode', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('related_accession', models.CharField(blank=True, default='NA', max_length=2000, null=True)),
                ('reference', models.TextField(blank=True, default='NA', null=True)),
                ('doi', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('note', models.TextField(blank=True, default='NA', null=True)),
            ],
            options={
                'ordering': ['host_order', 'host_family', 'host_species'],
            },
        ),
        migrations.AddIndex(
            model_name='symbiont',
            index=models.Index(fields=['host_order', 'host_family', 'host_species'], name='symbiont_sy_host_or_25f3ab_idx'),
        ),
    ]
