# Generated by Django 4.2 on 2024-12-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiont', '0003_alter_symbiont_options_symbiont_genome_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbiont',
            name='genome_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
