# Generated by Django 4.2 on 2025-01-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbiont', '0004_alter_symbiont_genome_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbiont',
            name='localization',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AddField(
            model_name='symbiont',
            name='transmission_mode',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
