# Generated by Django 4.2 on 2025-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(db_index=True, max_length=100, unique=True)),
                ('assay_type', models.CharField(blank=True, max_length=100, null=True)),
                ('biosample', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('center_name', models.CharField(blank=True, max_length=500, null=True)),
                ('instrument', models.CharField(blank=True, max_length=200, null=True)),
                ('library_layout', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_spot_len', models.CharField(blank=True, max_length=20, null=True)),
                ('bases', models.BigIntegerField(blank=True, null=True)),
                ('bioproject', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('classification', models.CharField(blank=True, max_length=200, null=True)),
                ('geo_loc_name_country', models.CharField(blank=True, db_index=True, max_length=200, null=True)),
                ('geo_loc_name_country_continent', models.CharField(blank=True, max_length=200, null=True)),
                ('collection_date', models.CharField(blank=True, max_length=100, null=True)),
                ('geo_loc_name', models.CharField(blank=True, max_length=500, null=True)),
                ('lat_lon', models.CharField(blank=True, max_length=200, null=True)),
                ('host', models.CharField(blank=True, db_index=True, max_length=500, null=True)),
                ('host_order', models.CharField(blank=True, max_length=200, null=True)),
                ('host_family', models.CharField(blank=True, max_length=200, null=True)),
                ('env_broad_scale', models.CharField(blank=True, max_length=500, null=True)),
                ('env_local_scale', models.CharField(blank=True, max_length=500, null=True)),
                ('env_medium', models.CharField(blank=True, max_length=500, null=True)),
                ('host_sex', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('doi', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'ordering': ['run', 'geo_loc_name_country', 'host', 'collection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='amplicon',
            index=models.Index(fields=['run', 'geo_loc_name_country', 'host', 'collection_date'], name='amplicon_am_run_dd926c_idx'),
        ),
    ]
