# Generated by Django 4.2 on 2024-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amplicon',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(db_index=True, max_length=100, unique=True)),
                ('assay_type', models.CharField(default='NA', max_length=100)),
                ('biosample', models.CharField(db_index=True, max_length=100)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('center_name', models.CharField(default='NA', max_length=200)),
                ('instrument', models.CharField(default='NA', max_length=100)),
                ('library_layout', models.CharField(default='NA', max_length=50)),
                ('library_selection', models.CharField(default='NA', max_length=100)),
                ('platform', models.CharField(default='NA', max_length=100)),
                ('bioproject', models.CharField(db_index=True, default='NA', max_length=100)),
                ('geo_loc_name_country', models.CharField(db_index=True, default='NA', max_length=100)),
                ('geo_loc_name_country_continent', models.CharField(default='NA', max_length=100)),
                ('collection_date', models.CharField(db_index=True, default='NA', max_length=100)),
                ('geo_loc_name', models.CharField(default='NA', max_length=200)),
                ('biosample_model', models.CharField(default='NA', max_length=100)),
                ('lat_lon', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(db_index=True, default='NA', max_length=200)),
                ('isolation', models.CharField(db_index=True, default='NA', max_length=200)),
                ('env_broad_scale', models.CharField(default='NA', max_length=200)),
                ('env_local_scale', models.CharField(default='NA', max_length=200)),
                ('env_medium', models.CharField(default='NA', max_length=200)),
                ('host_sex', models.CharField(default='NA', max_length=50)),
                ('classification', models.CharField(default='NA', max_length=100)),
            ],
            options={
                'ordering': ['run', 'geo_loc_name_country', 'host', 'collection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='amplicon',
            index=models.Index(fields=['run', 'geo_loc_name_country', 'host', 'collection_date'], name='amplicon_am_run_dd926c_idx'),
        ),
    ]
