# Generated by Django 4.2 on 2025-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplicon', '0002_remove_amplicon_biosample_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amplicon',
            name='center_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='classification',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='doi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='env_broad_scale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='env_local_scale',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='env_medium',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='geo_loc_name_country',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='geo_loc_name_country_continent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='host_family',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='host_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='instrument',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='amplicon',
            name='lat_lon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
