# Generated by Django 4.2 on 2024-12-02 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('genome_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('metagenome_id', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.TextField(blank=True, null=True)),
                ('literature_name', models.CharField(blank=True, max_length=200, null=True)),
                ('reference', models.CharField(blank=True, max_length=200, null=True)),
                ('checkm_marker_lineage', models.CharField(blank=True, max_length=200, null=True)),
                ('checkm_genomes', models.IntegerField(blank=True, null=True)),
                ('checkm_markers', models.IntegerField(blank=True, null=True)),
                ('completeness', models.FloatField(blank=True, null=True)),
                ('contamination', models.FloatField(blank=True, null=True)),
                ('strain_heterogeneity', models.FloatField(blank=True, null=True)),
                ('quality_score', models.FloatField(blank=True, null=True)),
                ('gtdb_classification', models.TextField(blank=True, null=True)),
                ('gtdb_phylum', models.CharField(blank=True, max_length=100, null=True)),
                ('closest_genome_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('closest_genome_reference_radius', models.FloatField(blank=True, null=True)),
                ('closest_genome_ani', models.FloatField(blank=True, null=True)),
                ('closest_placement_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('classification_method', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['host', 'genome_id'],
            },
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['host', 'genome_id'], name='genome_geno_host_87ea29_idx'),
        ),
    ]
