# Generated by Django 4.2 on 2024-12-11 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genome',
            old_name='metagenome_id',
            new_name='reference_accession',
        ),
        migrations.RenameField(
            model_name='genome',
            old_name='literature_name',
            new_name='reference_name',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='id',
        ),
        migrations.RemoveField(
            model_name='genome',
            name='reference',
        ),
        migrations.AddField(
            model_name='genome',
            name='reference_genus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='reference_order',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='reference_phylum',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='genome',
            name='source_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='classification_method',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='closest_genome_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='closest_placement_reference',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='genome',
            name='genome_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genome',
            name='gtdb_phylum',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['source_id'], name='genome_geno_source__f0aae7_idx'),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['reference_phylum'], name='genome_geno_referen_47ebcb_idx'),
        ),
        migrations.AddIndex(
            model_name='genome',
            index=models.Index(fields=['gtdb_phylum'], name='genome_geno_gtdb_ph_23962c_idx'),
        ),
    ]
