# Generated by Django 4.2 on 2024-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genome', '0002_rename_metagenome_id_genome_reference_accession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genome',
            name='reference_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
