# Generated by Django 4.2 on 2024-12-02 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genome', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gene_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('locus_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('gene_name', models.CharField(blank=True, max_length=100, null=True)),
                ('product', models.CharField(max_length=255)),
                ('start_position', models.IntegerField()),
                ('end_position', models.IntegerField()),
                ('strand', models.CharField(choices=[('+', 'Forward'), ('-', 'Reverse')], max_length=1)),
                ('sequence', models.TextField()),
                ('function', models.TextField(blank=True, null=True)),
                ('ec_number', models.CharField(blank=True, max_length=50, null=True)),
                ('go_terms', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='genes', to='genome.genome')),
            ],
            options={
                'ordering': ['genome', 'start_position'],
            },
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['genome', 'start_position'], name='gene_gene_genome__7470c5_idx'),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['gene_name'], name='gene_gene_gene_na_2ab4d6_idx'),
        ),
        migrations.AddIndex(
            model_name='gene',
            index=models.Index(fields=['locus_tag'], name='gene_gene_locus_t_605647_idx'),
        ),
    ]
