# Generated by Django 4.2 on 2025-01-29 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gene',
            new_name='custom_nr_id_idx',
            old_name='gene_gene_nr_id_12e816_idx',
        ),
        migrations.AlterField(
            model_name='gene',
            name='bigg_reaction',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cazy',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gene',
            name='kegg_ko',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='kegg_tc',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='seed_ortholog',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='gene',
            unique_together={('source_id', 'gene_id')},
        ),
    ]
