# Generated by Django 4.2 on 2025-01-29 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0002_rename_gene_gene_nr_id_12e816_idx_custom_nr_id_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='cog_category',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='ec_number',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='gene_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='gene',
            name='max_annot_lvl',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='nr_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='preferred_name',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='source_id',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
