# Generated by Django 4.2 on 2025-01-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0003_alter_gene_cog_category_alter_gene_ec_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gene',
            name='bigg_reaction',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cazy',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='cog_category',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='ec_number',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='kegg_ko',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='kegg_tc',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='max_annot_lvl',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='nr_annotation',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='nr_species',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='preferred_name',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='gene',
            name='seed_ortholog',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
