# Generated by Django 4.2 on 2025-01-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gene', '0004_alter_gene_bigg_reaction_alter_gene_cazy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gene',
            name='host',
            field=models.CharField(db_index=True, default='None', max_length=200),
        ),
    ]
