# Generated by Django 4.2 on 2025-01-31 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metagenome',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('run', models.CharField(db_index=True, max_length=100, unique=True)),
                ('assay_type', models.CharField(default='NA', max_length=100)),
                ('biosample', models.CharField(db_index=True, max_length=100)),
                ('bytes', models.BigIntegerField(blank=True, null=True)),
                ('center_name', models.CharField(max_length=200)),
                ('instrument', models.CharField(max_length=100)),
                ('library_layout', models.CharField(max_length=50)),
                ('library_selection', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=100)),
                ('bioproject', models.CharField(db_index=True, max_length=100)),
                ('geo_loc_name_country', models.CharField(db_index=True, max_length=100)),
                ('geo_loc_name_country_continent', models.CharField(max_length=100)),
                ('collection_date', models.CharField(db_index=True, default='NA', max_length=100)),
                ('geo_loc_name', models.CharField(max_length=200)),
                ('biosample_model', models.CharField(max_length=100)),
                ('lat_lon', models.CharField(blank=True, max_length=100, null=True)),
                ('host', models.CharField(db_index=True, max_length=200)),
                ('host_order', models.CharField(db_index=True, default='NA', max_length=200)),
                ('host_family', models.CharField(db_index=True, default='NA', max_length=200)),
                ('isolation', models.CharField(db_index=True, default='NA', max_length=200)),
                ('description', models.CharField(default='None', max_length=2000)),
                ('doi', models.CharField(db_index=True, default='None', max_length=200)),
            ],
            options={
                'ordering': ['run', 'geo_loc_name_country', 'host', 'collection_date'],
            },
        ),
        migrations.AddIndex(
            model_name='metagenome',
            index=models.Index(fields=['run', 'geo_loc_name_country', 'host', 'collection_date'], name='metagenome__run_4d4e4e_idx'),
        ),
    ]
